# Generated by Django 5.1.6 on 2025-02-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseconnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_committed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CriminalCrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_arrest', models.DateField()),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseconnect.crimes')),
            ],
        ),
        migrations.CreateModel(
            name='Criminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Criminal',
        ),
        migrations.AddField(
            model_name='criminalcrime',
            name='criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseconnect.criminals'),
        ),
    ]
