# Generated by Django 5.1.6 on 2025-02-14 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseconnect', '0002_crimenews_crimes_criminalcrime_criminals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_occurred', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('photo_url', models.URLField()),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='crimenews',
            old_name='published_date',
            new_name='published_at',
        ),
        migrations.RemoveField(
            model_name='criminalcrime',
            name='date_of_arrest',
        ),
        migrations.AlterField(
            model_name='crimenews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='criminalcrime',
            name='crime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseconnect.crime'),
        ),
        migrations.AlterField(
            model_name='criminalcrime',
            name='criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseconnect.criminal'),
        ),
        migrations.DeleteModel(
            name='Crimes',
        ),
        migrations.DeleteModel(
            name='Criminals',
        ),
    ]
